/**
 * MyKKTF Data Classification Engine
 * Aligns with Malaysian PDPA 2010 (Act 709) and PDPA (Amendment) Act 2024 principles.
 */

export const DATA_CLASSIFICATIONS = {
  PUBLIC: 'PUBLIC',
  INTERNAL: 'INTERNAL',
  CONFIDENTIAL: 'CONFIDENTIAL',
  SENSITIVE: 'SENSITIVE',
};

export const CLASSIFICATION_LABELS = {
  PUBLIC: 'Awam / Public',
  INTERNAL: 'Dalaman / Internal',
  CONFIDENTIAL: 'Sulit / Confidential',
  SENSITIVE: 'Sensitif / Sensitive High-Risk',
};

export const CLASSIFICATION_BADGES = {
  PUBLIC: 'bg-green-100 text-green-800 border-green-300 dark:bg-green-950/40 dark:text-green-300',
  INTERNAL: 'bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-950/40 dark:text-blue-300',
  CONFIDENTIAL: 'bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950/40 dark:text-amber-300',
  SENSITIVE: 'bg-rose-100 text-rose-800 border-rose-300 dark:bg-rose-950/40 dark:text-rose-300',
};

/**
 * Entity Field Level Classification Dictionary
 */
export const ENTITY_DATA_CLASSIFICATIONS = {
  Student: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    full_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    matric_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    ic_passport: DATA_CLASSIFICATIONS.SENSITIVE,
    email: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    phone_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    gender: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    race: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    religion: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    date_of_birth: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    faculty: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    programme: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    year_of_study: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    block: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    room_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    bed_letter: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    status: DATA_CLASSIFICATIONS.INTERNAL,
    emergency_contact_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    emergency_contact_phone: DATA_CLASSIFICATIONS.SENSITIVE,
    emergency_relationship: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    parent_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    parent_phone: DATA_CLASSIFICATIONS.SENSITIVE,
    parent_occupation: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    parent_income: DATA_CLASSIFICATIONS.SENSITIVE,
    address: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    blood_type: DATA_CLASSIFICATIONS.SENSITIVE,
    medical_condition: DATA_CLASSIFICATIONS.SENSITIVE,
    disability_info: DATA_CLASSIFICATIONS.SENSITIVE,
    allergies: DATA_CLASSIFICATIONS.SENSITIVE,
    vehicle_plate: DATA_CLASSIFICATIONS.CONFIDENTIAL,
  },
  DisciplineRecord: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    student_id: DATA_CLASSIFICATIONS.INTERNAL,
    student_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    matric_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    offence_type: DATA_CLASSIFICATIONS.SENSITIVE,
    offence_date: DATA_CLASSIFICATIONS.SENSITIVE,
    location: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    penalty: DATA_CLASSIFICATIONS.SENSITIVE,
    demerit_points: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    warden_notes: DATA_CLASSIFICATIONS.SENSITIVE,
    hearing_details: DATA_CLASSIFICATIONS.SENSITIVE,
    status: DATA_CLASSIFICATIONS.SENSITIVE,
    appeal_status: DATA_CLASSIFICATIONS.SENSITIVE,
  },
  Complaint: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    student_id: DATA_CLASSIFICATIONS.INTERNAL,
    student_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    matric_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    category: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    subject: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    description: DATA_CLASSIFICATIONS.SENSITIVE,
    welfare_flag: DATA_CLASSIFICATIONS.SENSITIVE,
    psychological_flag: DATA_CLASSIFICATIONS.SENSITIVE,
    status: DATA_CLASSIFICATIONS.INTERNAL,
    admin_response: DATA_CLASSIFICATIONS.CONFIDENTIAL,
  },
  LeaveApplication: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    student_id: DATA_CLASSIFICATIONS.INTERNAL,
    student_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    matric_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    start_date: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    end_date: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    reason: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    destination: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    emergency_contact: DATA_CLASSIFICATIONS.SENSITIVE,
    status: DATA_CLASSIFICATIONS.INTERNAL,
  },
  CheckIn: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    student_id: DATA_CLASSIFICATIONS.INTERNAL,
    student_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    room_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    check_in_date: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    key_received: DATA_CLASSIFICATIONS.INTERNAL,
  },
  CheckOut: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    student_id: DATA_CLASSIFICATIONS.INTERNAL,
    student_name: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    room_number: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    check_out_date: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    deposit_refund_status: DATA_CLASSIFICATIONS.SENSITIVE,
    key_returned: DATA_CLASSIFICATIONS.INTERNAL,
    room_condition: DATA_CLASSIFICATIONS.INTERNAL,
  },
  AuditLog: {
    id: DATA_CLASSIFICATIONS.INTERNAL,
    event_id: DATA_CLASSIFICATIONS.INTERNAL,
    actor_user_id: DATA_CLASSIFICATIONS.INTERNAL,
    actor_role: DATA_CLASSIFICATIONS.INTERNAL,
    action_type: DATA_CLASSIFICATIONS.INTERNAL,
    resource_type: DATA_CLASSIFICATIONS.INTERNAL,
    resource_id: DATA_CLASSIFICATIONS.INTERNAL,
    affected_user_id: DATA_CLASSIFICATIONS.INTERNAL,
    result: DATA_CLASSIFICATIONS.INTERNAL,
    details: DATA_CLASSIFICATIONS.CONFIDENTIAL,
    timestamp: DATA_CLASSIFICATIONS.INTERNAL,
  },
  Announcement: {
    id: DATA_CLASSIFICATIONS.PUBLIC,
    title: DATA_CLASSIFICATIONS.PUBLIC,
    content: DATA_CLASSIFICATIONS.PUBLIC,
    target_audience: DATA_CLASSIFICATIONS.PUBLIC,
    created_at: DATA_CLASSIFICATIONS.PUBLIC,
  },
  Event: {
    id: DATA_CLASSIFICATIONS.PUBLIC,
    title: DATA_CLASSIFICATIONS.PUBLIC,
    description: DATA_CLASSIFICATIONS.PUBLIC,
    event_date: DATA_CLASSIFICATIONS.PUBLIC,
    venue: DATA_CLASSIFICATIONS.PUBLIC,
    merit_points: DATA_CLASSIFICATIONS.PUBLIC,
  },
};

/**
 * Get classification of a specific entity field
 */
export function getFieldClassification(entityName, fieldName) {
  return ENTITY_DATA_CLASSIFICATIONS[entityName]?.[fieldName] || DATA_CLASSIFICATIONS.INTERNAL;
}
