import React, { useState, useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import PageHeader from '@/components/shared/PageHeader';
import EmptyState from '@/components/shared/EmptyState';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { useToast } from '@/components/ui/use-toast';
import { Plus, ClipboardCheck, QrCode, ScanLine } from 'lucide-react';

const statusBadge = { Present: 'bg-green-100 text-green-700', Absent: 'bg-red-100 text-red-700', Late: 'bg-yellow-100 text-yellow-700' };
const ADMIN_ROLES = ['warden', 'admin', 'staff'];

export default function AttendancePage() {
  const [records, setRecords] = useState([]);
  const [students, setStudents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [qrScanOpen, setQrScanOpen] = useState(false);
  const [qrToken, setQrToken] = useState('');
  const [currentUser, setCurrentUser] = useState(null);
  const [myStudent, setMyStudent] = useState(null);
  const [activeEvent, setActiveEvent] = useState({ event_type: 'Assembly', event_name: '', attendance_date: new Date().toISOString().split('T')[0] });
  const [form, setForm] = useState({ student_id: '', event_type: 'Assembly', event_name: '', attendance_date: new Date().toISOString().split('T')[0], method: 'Manual', status: 'Present' });
  const { toast } = useToast();

  const isAdmin = currentUser && ADMIN_ROLES.includes(currentUser.role);

  useEffect(() => { init(); }, []);
  async function init() {
    setLoading(true);
    const user = await base44.auth.me();
    setCurrentUser(user);
    const isAdminRole = ADMIN_ROLES.includes(user?.role);
    const [a, s] = await Promise.all([
      base44.entities.Attendance.list('-created_date'),
      isAdminRole ? base44.entities.Student.list() : Promise.resolve([])
    ]);
    setRecords(a);
    setStudents(s);
    if (!isAdminRole) {
      const studs = await base44.entities.Student.filter({ email: user.email });
      setMyStudent(studs[0] || null);
    }
    setLoading(false);
  }

  async function handleAdminSubmit() {
    if (!form.student_id || !form.event_name || !form.attendance_date) { toast({ title: 'Fill required fields', variant: 'destructive' }); return; }
    const student = students.find(s => s.id === form.student_id);
    await base44.entities.Attendance.create({ ...form, student_name: student?.full_name || '' });
    toast({ title: 'Attendance recorded' });
    setDialogOpen(false);
    init();
  }

  // Student QR self-check-in: they enter the event token (QR code value) generated by admin
  async function handleQrCheckIn() {
    if (!qrToken.trim()) { toast({ title: 'Enter the event code from the QR', variant: 'destructive' }); return; }
    if (!myStudent) { toast({ title: 'Student profile not found', variant: 'destructive' }); return; }
    // Token format: eventName|eventType|date  (admin displays QR with this value)
    const parts = qrToken.split('|');
    if (parts.length < 3) { toast({ title: 'Invalid QR code / event token', variant: 'destructive' }); return; }
    const [event_name, event_type, attendance_date] = parts;
    // Check if already registered
    const existing = records.find(r => r.student_id === myStudent.id && r.event_name === event_name && r.attendance_date === attendance_date);
    if (existing) { toast({ title: 'Already registered for this event' }); setQrScanOpen(false); return; }
    await base44.entities.Attendance.create({ student_id: myStudent.id, student_name: myStudent.full_name, event_type, event_name, attendance_date, method: 'QR Code', status: 'Present' });
    toast({ title: 'Attendance recorded via QR!' });
    setQrScanOpen(false);
    setQrToken('');
    init();
  }

  if (loading) return <div className="flex items-center justify-center h-64"><div className="w-8 h-8 border-4 border-muted border-t-primary rounded-full animate-spin" /></div>;

  return (
    <div>
      <PageHeader
        title="Attendance Tracking"
        description={isAdmin ? "Record and manage event attendance" : "Your attendance records"}
        actions={
          <div className="flex gap-2">
            {!isAdmin && myStudent && (
              <Button size="sm" variant="outline" onClick={() => setQrScanOpen(true)}>
                <QrCode className="w-4 h-4 mr-1.5" /> Scan QR / Enter Code
              </Button>
            )}
            {isAdmin && (
              <Button size="sm" onClick={() => { setForm({ student_id: '', event_type: 'Assembly', event_name: '', attendance_date: new Date().toISOString().split('T')[0], method: 'Manual', status: 'Present' }); setDialogOpen(true); }}>
                <Plus className="w-4 h-4 mr-1.5" /> Record Attendance
              </Button>
            )}
          </div>
        }
      />

      {/* QR Token generation helper for admin */}
      {isAdmin && (
        <div className="mb-5 bg-card border border-border rounded-xl p-4">
          <p className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1.5"><ScanLine className="w-3.5 h-3.5" /> QR Event Code Generator</p>
          <p className="text-xs text-muted-foreground mb-3">Generate a token to display as a QR code for students to self-register.</p>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
            <Input placeholder="Event Name e.g. Morning Assembly" className="h-9 text-sm" value={activeEvent.event_name} onChange={e => setActiveEvent(a => ({ ...a, event_name: e.target.value }))} />
            <Select value={activeEvent.event_type} onValueChange={v => setActiveEvent(a => ({ ...a, event_type: v }))}>
              <SelectTrigger className="h-9 text-sm"><SelectValue /></SelectTrigger>
              <SelectContent>{['Assembly','Briefing','Emergency Drill','Sports Activity','Other'].map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent>
            </Select>
            <Input type="date" className="h-9 text-sm" value={activeEvent.attendance_date} onChange={e => setActiveEvent(a => ({ ...a, attendance_date: e.target.value }))} />
          </div>
          {activeEvent.event_name && (
            <div className="mt-3 p-3 bg-muted rounded-lg text-center">
              <p className="text-[10px] text-muted-foreground mb-1">Share this token with students (display as QR):</p>
              <code className="text-sm font-bold text-primary break-all">{`${activeEvent.event_name}|${activeEvent.event_type}|${activeEvent.attendance_date}`}</code>
            </div>
          )}
        </div>
      )}

      {records.length === 0 ? <EmptyState icon={ClipboardCheck} title="No attendance records" /> : (
        <div className="bg-card border border-border rounded-xl overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead><tr className="border-b bg-muted/50">
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground uppercase">Student</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground uppercase hidden sm:table-cell">Event</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground uppercase">Type</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground uppercase hidden md:table-cell">Date</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground uppercase hidden md:table-cell">Method</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-muted-foreground uppercase">Status</th>
              </tr></thead>
              <tbody>
                {records.map(r => (
                  <tr key={r.id} className="border-b last:border-0 hover:bg-muted/30">
                    <td className="px-4 py-3 font-medium">{r.student_name}</td>
                    <td className="px-4 py-3 text-muted-foreground hidden sm:table-cell">{r.event_name}</td>
                    <td className="px-4 py-3 text-muted-foreground">{r.event_type}</td>
                    <td className="px-4 py-3 text-muted-foreground hidden md:table-cell">{r.attendance_date}</td>
                    <td className="px-4 py-3 text-muted-foreground hidden md:table-cell">{r.method}</td>
                    <td className="px-4 py-3"><span className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${statusBadge[r.status]}`}>{r.status}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Admin: manual record dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>Record Attendance</DialogTitle></DialogHeader>
          <div className="space-y-3 mt-2">
            <div><Label className="text-xs">Student *</Label>
              <Select value={form.student_id} onValueChange={v => setForm({ ...form, student_id: v })}>
                <SelectTrigger className="h-9 text-sm mt-1"><SelectValue placeholder="Select student" /></SelectTrigger>
                <SelectContent>{students.map(s => <SelectItem key={s.id} value={s.id}>{s.full_name}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div><Label className="text-xs">Event Type</Label>
              <Select value={form.event_type} onValueChange={v => setForm({ ...form, event_type: v })}>
                <SelectTrigger className="h-9 text-sm mt-1"><SelectValue /></SelectTrigger>
                <SelectContent>{['Assembly','Briefing','Emergency Drill','Sports Activity','Other'].map(t => <SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div><Label className="text-xs">Event Name *</Label><Input value={form.event_name} onChange={e => setForm({ ...form, event_name: e.target.value })} className="h-9 text-sm mt-1" /></div>
            <div><Label className="text-xs">Date *</Label><Input type="date" value={form.attendance_date} onChange={e => setForm({ ...form, attendance_date: e.target.value })} className="h-9 text-sm mt-1" /></div>
            <div><Label className="text-xs">Method</Label>
              <Select value={form.method} onValueChange={v => setForm({ ...form, method: v })}>
                <SelectTrigger className="h-9 text-sm mt-1"><SelectValue /></SelectTrigger>
                <SelectContent>{['QR Code','Manual','Event'].map(m => <SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent>
              </Select>
            </div>
            <div><Label className="text-xs">Status</Label>
              <Select value={form.status} onValueChange={v => setForm({ ...form, status: v })}>
                <SelectTrigger className="h-9 text-sm mt-1"><SelectValue /></SelectTrigger>
                <SelectContent>{['Present','Absent','Late'].map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent>
              </Select>
            </div>
          </div>
          <div className="flex justify-end gap-2 mt-4"><Button variant="outline" size="sm" onClick={() => setDialogOpen(false)}>Cancel</Button><Button size="sm" onClick={handleAdminSubmit}>Save</Button></div>
        </DialogContent>
      </Dialog>

      {/* Student: QR token check-in dialog */}
      <Dialog open={qrScanOpen} onOpenChange={setQrScanOpen}>
        <DialogContent className="max-w-sm">
          <DialogHeader><DialogTitle className="flex items-center gap-2"><QrCode className="w-4 h-4" /> Register via Event QR</DialogTitle></DialogHeader>
          <div className="space-y-3 mt-2">
            <p className="text-xs text-muted-foreground">Scan the QR code shown at the event, or enter the event token provided by your warden/admin.</p>
            <div><Label className="text-xs">Event Token *</Label>
              <Input value={qrToken} onChange={e => setQrToken(e.target.value)} placeholder="e.g. Morning Assembly|Assembly|2026-06-12" className="h-9 text-sm mt-1 font-mono" />
            </div>
          </div>
          <div className="flex justify-end gap-2 mt-4"><Button variant="outline" size="sm" onClick={() => setQrScanOpen(false)}>Cancel</Button><Button size="sm" onClick={handleQrCheckIn}>Register Attendance</Button></div>
        </DialogContent>
      </Dialog>
    </div>
  );
}